### ISSUE TITLE
ENH: better run-id strings

### ISSUE THREAD

**Issue by dengemann** [dengemann/meeg-preprocessing#10]
instead of using the hex, we could do 

YYYY-MM-DD_HH-MM-SS based on the time stamp. This would be more human readable and garuanteed to be sorted in the file system.

cc @cmoutard @kingjr

**Comment by kingjr** [comment]
Absolutely. Small point, why using both  '-' and '_'?

**Comment by dengemann** [comment]
> Small point, why using both '-' and '_'?

on reading different versions I found easier to parse

**Comment by kingjr** [comment]
Is it me, or it is set to Paris time independently of where you are?

**Comment by dengemann** [comment]
> Is it me, or it is set to Paris time independently of where you are?

?

**Comment by kingjr** [comment]
It's probably me, right? I guess I need to tell python what time it is around here ?

![date](https://cloud.githubusercontent.com/assets/4881164/7758520/3d756c54-ffd8-11e4-9a08-53e61e3e7038.png)
