### ISSUE TITLE
Example plot_preprocess_filter_ica.py doesn't work

### ISSUE THREAD

**Issue by LaetitiaG** [dengemann/meeg-preprocessing#18]
Hi,
I tried to launch the example script plot_preprocess_filter_ica.py but I got the following error at the check_apply_filter function line: " 'RawFIFF' object has no attribute 'plot_psd' ". Indeed you cannot apply this function to the raw file... Could it be a version problem (I'm using 0.9.dev)?
By the way, I'm wondering if this example is doing the same thing than the example in mne-python (Compute ICA components on raw data). I saw that here you're doing some supplementary filtering, why is it for?
Thanks,
Laetitia

**Comment by dengemann** [comment]
@LaetitiaG it seems your version is out-dated. You should use at least the new MNE 0.9 release or MNE 0.10-dev.

>  I saw that here you're doing some supplementary filtering, why is it for?

Just to show people that you can do some filtering diagnostic plots too (before/after power spectrum).
Also filtering improves the ICA results very often.

**Comment by LaetitiaG** [comment]
True, I upgraded up to 0.9, but now I have new errors at the check_apply_filter function line: "TclError: this isn't a Tk application" and then ipython closed with the following message: 

The program 'python' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 7488 error_code 3 request_code 15 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

Am I missing something, maybe related to the html reporting function?

**Comment by dengemann** [comment]
No it's an Ipython problem. Try the different backends when using ipython
--pylab, i.e., tk, qt, qt4, ...

2015-06-22 18:36 GMT+02:00 LaetitiaG notifications@github.com:

**Comment by LaetitiaG** [comment]
Great, it works when I open ipython with ipython --pylab qt. However, I got a new (last?) error, saying that "There is no ECG channel" when running compute_ica with ch_types = 'eeg'. What could be the solution?

**Comment by dengemann** [comment]
> I got a new (last?) error, saying that "There is no ECG channel" when running compute_ica with ch_types = 'eeg'. What could be the solution?

Mhmm I think this one was fixed, a picking issue. Normally the magnetometers are used to compute an artificial ECG of you don't have one. @cmoutard how did you deal with it?

**Comment by LaetitiaG** [comment]
But I do have ECG recording (I guess there were successfully used when running compute_ica for 'meg', because no error arose).

**Comment by dengemann** [comment]
> But I do have ECG recording (I guess there were successfully used when running compute_ica for 'meg', because no error arose).

**Comment by dengemann** [comment]
Mhmm, but it checks for ECG ...

https://github.com/dengemann/meeg-preprocessing/blob/master/meeg_preprocessing/preprocessing.py#L208

It looks like your ECG channel is not declared for MEG the MAG mean is used.
What does `'ecg' in raw` return?
You can set channel types using `raw.set_channel_types({'ECG 001': 'ecg'})` or whichever channel name.

**Comment by LaetitiaG** [comment]
Edit: I'm not looking at my data but at the mne.datasets.sample test data, so actually, I don't know whether there was ECG recording.

'ecg' in raw return False. And when I have a look at raw.ch_names, there is no ECG channel in the list.

**Comment by dengemann** [comment]
> Edit: I'm not looking at my data but at the mne.datasets.sample test
> data, so actually, I don't know whether there was ECG recording.

Are you saying the example fails on the sample data?

2015-06-23 16:28 GMT+02:00 LaetitiaG notifications@github.com:

**Comment by LaetitiaG** [comment]
Yes...

**Comment by dengemann** [comment]
Ok, thanks for reporting this is a bug / weakness. It used to work before.

2015-06-23 16:34 GMT+02:00 LaetitiaG notifications@github.com:

**Comment by dengemann** [comment]
solved, but you'll need the current MNE version + wair for these changes to be merged.

https://github.com/mne-tools/mne-python/pull/2607
