### ISSUE TITLE
Pick mismatch between raw and ecg_epochs in compute_ica()

### ISSUE THREAD

**Issue by cmoutard** [dengemann/meeg-preprocessing#6]
# Pick mismatch between raw and ecg_epochs

raw is used to create ecp_epochs (see first line of code below).
raw could include all the channels (i.e. STI, MISC,...), contrary to the output of create_ecg_epochs() (here ecg_epochs) which only includes MAG, GRAD and EEG.
Because of this, a mismatch may appear between the argumtant picks (based on raw) in compute_ica() used in the bottom line of the code below and the actual channels of ecg_epochs.

For instance :
len(raw.ch_names) = 405
len(ecp_epochs.ch_names) = 306
raw.ch_names[405] = 'EEG60'
ecp_epochs.ch_names[306] = 'EEG60'
So for the channel EEG60, the "picks" would point to index 405 according to raw which is out of the bound for ecg_epochs.

```
def compute_ica(raw, subject, n_components=0.99, picks=None, decim=None,
                reject=None, ecg_tmin=-0.5, ecg_tmax=0.5, eog_tmin=-0.5,
                eog_tmax=0.5, n_max_ecg=3, n_max_eog=1,
                n_max_ecg_epochs=200, img_scale=1.0,
                report=None):

...

    ecg_epochs = create_ecg_epochs(raw, tmin=ecg_tmin, tmax=ecg_tmax,
                                   picks=None, reject={'mag': 5e-12})
    n_ecg_epochs_found = len(ecg_epochs.events)
    n_max_ecg_epochs = min(n_max_ecg_epochs, n_ecg_epochs_found)
    sel_ecg_epochs = np.arange(n_ecg_epochs_found)
    rng = np.random.RandomState(42)
    rng.shuffle(sel_ecg_epochs)
    ecg_epochs = ecg_epochs[sel_ecg_epochs[:n_max_ecg_epochs]]

    ecg_inds, scores = ica.find_bads_ecg(ecg_epochs, method='ctps')
    if len(ecg_inds) > 0:
        ecg_evoked = ecg_epochs.average(picks=picks)
```

**Comment by cmoutard** [comment]
@dengemann

**Comment by dengemann** [comment]
Yes tomorow, virtually offline.

**Comment by dengemann** [comment]
@cmoutard thanks. I reproduced the problem locally.

**Comment by cmoutard** [comment]
Unfortunately, the problem is still there :

![error_outofrange](https://cloud.githubusercontent.com/assets/7878675/6772338/dc41c370-d0fb-11e4-8b0b-04341212181a.png)
